import Navbar from '@/components/navbar';
import './globals.css';
import { Noto_Sans_KR } from 'next/font/google';
import Footer from '@/components/footer';

const notoSansKR = Noto_Sans_KR({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: '리베동물병원',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={notoSansKR.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
